// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package mining

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "mining", asset.ModuleFieldsPri, AssetMining); err != nil {
		panic(err)
	}
}

// AssetMining returns asset data.
// This is the base64 encoded zlib format compressed contents of module/mining.
func AssetMining() string {
	return "eJzElr1y2zAMx3c/BS5TO+QFNHRp73od0su1cTOzFCSxJkUeCEXnt+9RshzFpr5qqcHgQaDw/wkgAN/DAY8JGFWqMt8BsGKNCdy1D+52AIQahccEfiOLHUCKXpJyrGyZwKcdAJzeBmPTSuMOIFOoU580vnsohcGeQjA+OkwgJ1u505NI1Ldx+rE8Cz4/jEULdsndWVSptRAXDDIp6XuOS4yLz0J64xnimdAO9tDm0duMa0EIqswsGRGOX5yNIfWxwu+VsyM74LG2lEb8E3zBvguDYLOu5h3rIMkLkr/mXwnmVxt8CU/lWI3kRtvzJV3Ism8CL0Fx1upt8vJorV5CItKU0PttYPYeqVNYBKVzS4oLsw3Wj6psOM4yS9hqS4ervl8J7LmJ3QhNIXU4uavWmkFfH/eQ4ouSt4wfFfv0WxvsWxrSkbvqxPeOw28GBKNxSIKryC0aK89Mki9tiZ5GVYbK1OeUNvoqTBVsJmewz5YQZKGcR57IS2+xorF03JjsoRGZxdZxZWJ4l/373Q5dl4kSvENMQXhwSBJLVnqYpBC+IMFb7LKAMxj+dX3VIyPwNnFpS1+Z5lirE3JSC2aR44fnj4NMvohN7RX67Wcx/ocMZrabkBIdY2z+wIoX+8my0GexNi2x9f4KRvgH5f8C68TmgHkWkSbYgqpR6pD+BgAA//9WwxPE"
}
