// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package mining

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "mining", asset.ModuleFieldsPri, AssetMining); err != nil {
		panic(err)
	}
}

// AssetMining returns asset data.
// This is the base64 encoded zlib format compressed contents of module/mining.
func AssetMining() string {
	return "eJzElr2SmzAQx3ueYueqpLgXoEiTzGRSXOYmOSf1RiygnIQ00nIev31GYPk4WxiIIdnCBSv2//N+aLmHZzrkoGUjmyoDYMmKcrjrH9xlAI4UoaccfhFjBlCQF05alqbJ4UMGAMe3QZuiVZQBlJJU4fPOdw8NahooBOODpRwqZ1p7fJKI+jbOMJZn5NPDVLRg59zRkkq9hbigiZ0UfuA4xzj7W+TeeMZ4JrSDPfR59KbkPToC2ZTGaQzHz86mkIZY4ffCGcme6bA3rkj4J/iCfUVNYMpY88g6SvJCzl/yrwTzow++hKe1LK/kRplTky5k2XWBl6BYY9Q2eXk0Ri0hwaJw5P02MDtPLiosglKVcZJrvQ3Wt7bpOE4yU2yRq7LtWgP/+XEHBb1Iccusy1QCbu3mL0VIR2XbI99/vGlmQDBpSw65TbTTtfLMJPnUl+jpqspYmYacwiRfhamCzeQM9tE4AlFL64kn8jLYYqSNO2xM9tCJzGKLXCWOL46/7+0wdSU24C1RAejBkhPUsFTjJDX62iFvsTgCzmj4112xv/jOWEtcmMa3ujvW64Sc7JEZK3r38/0ok69T1/cK8/a9vv71AzPHDYUgy5S6f2DFxn4yjOok1qcltUtfwRz9JvGvwKLYHDDPmBiCLag6pYj0JwAA//925e/x"
}
